#include "esolver_lj.h"

#include "source_base/global_variable.h"
#include "source_cell/mdcell.h"
#include "source_cell/module_neighlist/neighbor_search.h"
#include "source_cell/module_neighlist/neighbor_types.h"
#include "source_io/module_parameter/parameter.h"
#include "source_cell/cif_io.h"
#include "source_io/module_output/output_log.h"
#ifdef __MPI
#include <mpi.h>
#endif

#include <algorithm>
#include <array>
#include <cmath>
#include <vector>

namespace ModuleESolver
{
void ESolver_LJ::before_all_runners(BaseCell& cell, const Input_para& inp)
{
    this->inp_ = &inp;
    lj_potential = 0.0;
    lj_virial.create(3, 3);

    if (cell.kind() == BaseCell::Kind::mdcell)
    {
        MDCell& mdcell = static_cast<MDCell&>(cell);
        double cutoff = 0.0;
        for (std::size_t i = 0; i < inp.mdp.lj_rcut.size(); ++i)
        {
            cutoff = std::max(cutoff, inp.mdp.lj_rcut[i] * ModuleBase::ANGSTROM_AU);
        }
        mdcell.set_neighbor_cutoff(cutoff);
        rcut_search_radius(static_cast<int>(mdcell.type_labels().size()), inp.mdp.lj_rcut);
        set_c6_c12(static_cast<int>(mdcell.type_labels().size()), inp.mdp.lj_rule, inp.mdp.lj_epsilon, inp.mdp.lj_sigma);
        cal_en_shift(static_cast<int>(mdcell.type_labels().size()), inp.mdp.lj_eshift);
        return;
    }

    UnitCell& ucell = static_cast<UnitCell&>(cell);
    lj_force.create(ucell.nat, 3);
    ModuleIO::CifParser::write(PARAM.globalv.global_out_dir + "STRU.cif",
                               ucell,
                               "# Generated by ABACUS ModuleIO::CifParser",
                               "data_?");
    rcut_search_radius(ucell.ntype, inp.mdp.lj_rcut);
    set_c6_c12(ucell.ntype, inp.mdp.lj_rule, inp.mdp.lj_epsilon, inp.mdp.lj_sigma);
    cal_en_shift(ucell.ntype, inp.mdp.lj_eshift);
}

void ESolver_LJ::runner(BaseCell& cell, const int istep)
{
    static_cast<void>(istep);

    lj_potential = 0.0;
    lj_virial.zero_out();

    if (cell.kind() == BaseCell::Kind::unitcell)
    {
        NeighborSearch neighbor_search;
        UnitCell& ucell = static_cast<UnitCell&>(cell);
        lj_force.zero_out();
        neighbor_search.init(ucell, search_radius);
        neighbor_search.build_neighbors();

        const NeighborList& neighbor_list = neighbor_search.get_neighbor_list();
        const std::vector<NeighborAtom>& inside_atoms = neighbor_search.get_inside_atoms();
        const std::vector<NeighborAtom>& all_atoms = neighbor_search.get_all_atoms();
        std::array<double, 9> virial{};
        std::vector<int> atom_offsets(ucell.ntype + 1, 0);
        for (int it = 0; it < ucell.ntype; ++it)
        {
            atom_offsets[it + 1] = atom_offsets[it] + ucell.atoms[it].na;
        }

        for (int local_i = 0; local_i < neighbor_list.get_ncentral_atoms(); ++local_i)
        {
            const NeighborAtom& center_atom = inside_atoms[static_cast<std::size_t>(local_i)];
            const int it = center_atom.atom_type;
            const int ia = center_atom.atom_index;
            const int iat = atom_offsets[it] + ia;
            const ModuleBase::Vector3<double> tau1(center_atom.position_x,
                                                    center_atom.position_y,
                                                    center_atom.position_z);
            for (int ad = 0; ad < neighbor_list.get_numneigh(local_i); ++ad)
            {
                const NeighborAtom& neighbor_atom = all_atoms[neighbor_list.get_firstneigh(local_i)[ad]];
                const ModuleBase::Vector3<double> tau2(neighbor_atom.position_x,
                                                        neighbor_atom.position_y,
                                                        neighbor_atom.position_z);
                const ModuleBase::Vector3<double> dtau = (tau1 - tau2) * ucell.lat0;
                const double distance = dtau.norm();
                if (distance < lj_rcut(it, neighbor_atom.atom_type))
                {
                    lj_potential += LJ_energy(distance, it, neighbor_atom.atom_type)
                                    - en_shift(it, neighbor_atom.atom_type);
                    const ModuleBase::Vector3<double> f_ij = LJ_force(dtau, it, neighbor_atom.atom_type);
                    lj_force(iat, 0) += f_ij.x;
                    lj_force(iat, 1) += f_ij.y;
                    lj_force(iat, 2) += f_ij.z;
                    for (int i = 0; i < 3; ++i)
                        for (int j = 0; j < 3; ++j) virial[i * 3 + j] += dtau[i] * f_ij[j];
                }
            }
        }

        lj_potential *= 0.5;
        for (int i = 0; i < 3; ++i)
            for (int j = 0; j < 3; ++j) lj_virial(i, j) = virial[i * 3 + j] / (2.0 * ucell.omega);
        GlobalV::ofs_running << " #TOTAL ENERGY# " << std::setprecision(11)
                             << lj_potential * ModuleBase::Ry_to_eV << " eV" << std::endl;
        return;
    }

    MDCell& mdcell = static_cast<MDCell&>(cell);
    if (!mdcell.has_neighbor_search())
    {
        ModuleBase::WARNING_QUIT("ESolver", "MDCell neighbors must be prepared by the caller before runner().");
    }

    std::vector<LocalAtom>& owned_atoms = mdcell.owned_atoms();
    for (std::size_t i = 0; i < owned_atoms.size(); ++i)
    {
        owned_atoms[i].force.set(0.0, 0.0, 0.0);
    }

    const NeighborSearch& neighbor_search = mdcell.neighbor_search();
    const NeighborList& neighbor_list = neighbor_search.get_neighbor_list();
    const std::vector<NeighborAtom>& all_atoms = neighbor_search.get_all_atoms();

    double local_potential = 0.0;
    std::array<double, 9> local_virial{};

    for (int local_i = 0; local_i < neighbor_list.get_ncentral_atoms(); ++local_i)
    {
        LocalAtom& center_atom = owned_atoms[static_cast<std::size_t>(local_i)];
        ModuleBase::Vector3<double> tau1(center_atom.cart.x, center_atom.cart.y, center_atom.cart.z);
        for (int ad = 0; ad < neighbor_list.get_numneigh(local_i); ++ad)
        {
            const NeighborAtom& neighbor_atom = all_atoms[neighbor_list.get_firstneigh(local_i)[ad]];
            ModuleBase::Vector3<double> tau2(neighbor_atom.position_x,
                                             neighbor_atom.position_y,
                                             neighbor_atom.position_z);
            ModuleBase::Vector3<double> dtau = (tau1 - tau2) * mdcell.lat0();
            const double distance = dtau.norm();
            if (distance < lj_rcut(center_atom.type, neighbor_atom.atom_type))
            {
                local_potential += LJ_energy(distance, center_atom.type, neighbor_atom.atom_type)
                                   - en_shift(center_atom.type, neighbor_atom.atom_type);
                ModuleBase::Vector3<double> f_ij = LJ_force(dtau, center_atom.type, neighbor_atom.atom_type);
                center_atom.force += f_ij;
                for (int i = 0; i < 3; ++i)
                {
                    for (int j = 0; j < 3; ++j)
                    {
                        local_virial[i * 3 + j] += dtau[i] * f_ij[j];
                    }
                }
            }
        }
    }

#ifdef __MPI
    MPI_Allreduce(MPI_IN_PLACE, &local_potential, 1, MPI_DOUBLE, MPI_SUM, mdcell.communicator());
    MPI_Allreduce(MPI_IN_PLACE,
                  local_virial.data(),
                  static_cast<int>(local_virial.size()),
                  MPI_DOUBLE,
                  MPI_SUM,
                  mdcell.communicator());
#endif

    lj_potential = local_potential / 2.0;
    for (int i = 0; i < 3; ++i)
    {
        for (int j = 0; j < 3; ++j)
        {
            lj_virial(i, j) = local_virial[i * 3 + j] / (2.0 * mdcell.omega());
        }
    }
}

double ESolver_LJ::cal_energy()
{
    return lj_potential;
}

void ESolver_LJ::cal_force(BaseCell& cell, ModuleBase::matrix& force)
{
    if (cell.kind() == BaseCell::Kind::unitcell)
    {
        UnitCell& ucell = static_cast<UnitCell&>(cell);
        force = lj_force;
        ModuleIO::print_force(GlobalV::ofs_running, ucell, "TOTAL-FORCE (eV/Angstrom)", force, false);
        return;
    }

    MDCell& mdcell = static_cast<MDCell&>(cell);
    force.create(mdcell.owned_atoms().size(), 3);
    for (int i = 0; i < mdcell.owned_atoms().size(); ++i)
    {
        force(i, 0) = mdcell.owned_atoms()[static_cast<std::size_t>(i)].force.x;
        force(i, 1) = mdcell.owned_atoms()[static_cast<std::size_t>(i)].force.y;
        force(i, 2) = mdcell.owned_atoms()[static_cast<std::size_t>(i)].force.z;
    }
}

void ESolver_LJ::cal_stress(BaseCell& cell, ModuleBase::matrix& stress)
{
    stress = lj_virial;

    if (cell.kind() == BaseCell::Kind::unitcell)
    {
        ModuleIO::print_stress("TOTAL-STRESS", stress, true, false, GlobalV::ofs_running);
    }
    else
    {
#ifdef __MPI
        if (static_cast<MDCell&>(cell).mpi_rank() == 0)
#endif
        {
            ModuleIO::print_stress("TOTAL-STRESS", stress, true, false, GlobalV::ofs_running);
        }
    }

    const double unit_transform = ModuleBase::RYDBERG_SI / pow(ModuleBase::BOHR_RADIUS_SI, 3) * 1.0e-8;
    const double external_stress[3] = {this->inp_->press1, this->inp_->press2, this->inp_->press3};
    for (int i = 0; i < 3; ++i)
    {
        stress(i, i) -= external_stress[i] / unit_transform;
    }
}

void ESolver_LJ::after_all_runners(BaseCell& cell)
{
    static_cast<void>(cell);

    GlobalV::ofs_running << "\n --------------------------------------------" << std::endl;
    GlobalV::ofs_running << std::setprecision(16);
    GlobalV::ofs_running << " !FINAL_ETOT_IS " << lj_potential * ModuleBase::Ry_to_eV << " eV" << std::endl;
    GlobalV::ofs_running << " --------------------------------------------\n\n" << std::endl;
}

void ESolver_LJ::others(BaseCell& cell, const int istep)
{
    static_cast<void>(istep);
    static_cast<void>(cell);
}

double ESolver_LJ::LJ_energy(const double& d, const int& i, const int& j) const
{
    assert(d > 1e-6); // avoid atom overlap
    const double r2 = d * d;
    const double r4 = r2 * r2;
    const double r6 = r2 * r4;
    return lj_c12(i, j) / (r6 * r6) - lj_c6(i, j) / r6;
}

ModuleBase::Vector3<double> ESolver_LJ::LJ_force(const ModuleBase::Vector3<double>& dr,
                                                 const int& i,
                                                 const int& j) const
{
    const double d = dr.norm();
    assert(d > 1e-6); // avoid atom overlap
    const double r2 = d * d;
    const double r4 = r2 * r2;
    const double r8 = r4 * r4;
    const double r14 = r8 * r4 * r2;
    double coff = 12.0 * lj_c12(i, j) / r14 - 6.0 * lj_c6(i, j) / r8;
    return dr * coff;
}

void ESolver_LJ::rcut_search_radius(const int& ntype, const std::vector<double>& rcut)
{
    lj_rcut.create(ntype, ntype);
    double rcut_max = 0.0;

    if (rcut.size() == 1)
    {
        rcut_max = rcut[0] * ModuleBase::ANGSTROM_AU;
        for (int i = 0; i < ntype; i++)
        {
            for (int j = 0; j <= i; j++)
            {
                lj_rcut(i, j) = rcut_max;
                lj_rcut(j, i) = rcut_max;
            }
        }
    }
    else if (rcut.size() == ntype * (ntype + 1) / 2)
    {
        for (int i = 0; i < ntype; i++)
        {
            for (int j = 0; j <= i; j++)
            {
                int k = i * (i + 1) / 2 + j;
                lj_rcut(i, j) = rcut[k] * ModuleBase::ANGSTROM_AU;
                lj_rcut(j, i) = lj_rcut(i, j);
                rcut_max = std::max(rcut_max, lj_rcut(i, j));
            }
        }
    }

    // set the search radius
    search_radius = rcut_max + 0.01;
}

void ESolver_LJ::set_c6_c12(const int& ntype,
                            const int& rule,
                            const std::vector<double>& epsilon,
                            const std::vector<double>& sigma)
{
    lj_c6.create(ntype, ntype);
    lj_c12.create(ntype, ntype);

    std::vector<double> lj_epsilon = epsilon;
    std::vector<double> lj_sigma = sigma;

    std::transform(begin(lj_epsilon), end(lj_epsilon), begin(lj_epsilon), [](double x) {
        return x / ModuleBase::Ry_to_eV;
    });
    std::transform(begin(lj_sigma), end(lj_sigma), begin(lj_sigma), [](double x) {
        return x * ModuleBase::ANGSTROM_AU;
    });

    if (lj_epsilon.size() != lj_sigma.size())
    {
        ModuleBase::WARNING_QUIT("ESolver_LJ", " the number of lj_epsilon should be equal to lj_sigma ");
    }
    // do not need any combination rules
    else if (lj_sigma.size() == ntype * (ntype + 1) / 2)
    {
        for (int i = 0; i < ntype; i++)
        {
            for (int j = 0; j <= i; j++)
            {
                int k = i * (i + 1) / 2 + j;
                double temp = pow(lj_sigma[k], 6);
                lj_c6(i, j) = 4.0 * lj_epsilon[k] * temp;
                lj_c12(i, j) = lj_c6(i, j) * temp;
                lj_c6(j, i) = lj_c6(i, j);
                lj_c12(j, i) = lj_c12(i, j);
            }
        }
    }
    // combination rule 1
    else if (lj_sigma.size() == ntype && rule == 1)
    {
        for (int i = 0; i < ntype; i++)
        {
            // first determine the diagonal elements
            double temp = pow(lj_sigma[i], 6);
            lj_c6(i, i) = 4.0 * lj_epsilon[i] * temp;
            lj_c12(i, i) = lj_c6(i, i) * temp;

            // then determine the non-diagonal elements
            for (int j = 0; j < i; j++)
            {
                lj_c6(i, j) = std::sqrt(lj_c6(i, i) * lj_c6(j, j));
                lj_c12(i, j) = std::sqrt(lj_c12(i, i) * lj_c12(j, j));
                lj_c6(j, i) = lj_c6(i, j);
                lj_c12(j, i) = lj_c12(i, j);
            }
        }
    }
    // combination rule 2
    else if (lj_sigma.size() == ntype && rule == 2)
    {
        for (int i = 0; i < ntype; i++)
        {
            for (int j = 0; j <= i; j++)
            {
                double sigma_ij = (lj_sigma[i] + lj_sigma[j]) / 2.0;
                double epsilon_ij = std::sqrt(lj_epsilon[i] * lj_epsilon[j]);

                double temp = pow(sigma_ij, 6);
                lj_c6(i, j) = 4.0 * epsilon_ij * temp;
                lj_c12(i, j) = lj_c6(i, j) * temp;
                lj_c6(j, i) = lj_c6(i, j);
                lj_c12(j, i) = lj_c12(i, j);
            }
        }
    }
}

void ESolver_LJ::cal_en_shift(const int& ntype, const bool& is_shift)
{
    en_shift.create(ntype, ntype);

    if (is_shift)
    {
        for (int i = 0; i < ntype; i++)
        {
            for (int j = 0; j <= i; j++)
            {
                en_shift(i, j) = LJ_energy(lj_rcut(i, j), i, j);
                en_shift(j, i) = en_shift(i, j);
            }
        }
    }
}
} // namespace ModuleESolver
