/**
 * @file esolver_dp.cpp
#include "source_io/module_parameter/parameter.h"
 * @brief Implementation of ESolver_DP class for DeePMD method.
 *
 * This file contains the implementation of the ESolver_DP class, which is used for solving the energy and forces in a
 * Deep Potential Molecular Dynamics (DeePMD) simulation.
 * DeePMD is a method for training deep neural networks to accurately predict the potential energy surface of a
 * molecular system.
 *
 * For more information about DeePMD, see the following reference:
 *
 * Han Wang, Linfeng Zhang, Jiequn Han, and Roberto Car.
 * "DeePMD-kit: A deep learning package for many-body potential energy representation and molecular dynamics,"
 * Computer Physics Communications 228, 178-184 (2018). https://doi.org/10.1016/j.cpc.2018.03.016
 *
 * @author YuLiu98
 * @date 2023-05-15
 */
#include "esolver_dp.h"
#include "source_base/parallel_common.h"
#include "source_base/timer.h"
#include "source_cell/mdcell.h"
#include "source_cell/module_neighlist/neighbor_search.h"
#include "source_cell/cif_io.h"
#include "source_io/module_output/output_log.h"
#include "source_io/module_parameter/parameter.h"

#include <algorithm>
#include <iomanip>
#include <array>
#include <sstream>
#include <unordered_map>

using namespace ModuleESolver;

void ESolver_DP::before_all_runners(BaseCell& basecell, const Input_para& inp)
{
    this->inp_ = &inp;
    dp_potential = 0;
    dp_virial.create(3, 3);
    rescaling = inp.mdp.dp_rescaling;
    fparam = inp.mdp.dp_fparam;
    aparam = inp.mdp.dp_aparam;

    if (basecell.kind() == BaseCell::Kind::mdcell)
    {
        MDCell& mdcell = static_cast<MDCell&>(basecell);
#ifdef __DPMD
        mdcell.set_neighbor_cutoff(dp.cutoff() * ModuleBase::ANGSTROM_AU);
        initialize_type_map_(mdcell.type_labels());
#else
        ModuleBase::WARNING_QUIT("ESolver_DP", "Please recompile with -D__DPMD");
#endif
        return;
    }

    UnitCell& ucell = static_cast<UnitCell&>(basecell);
    dp_force.create(ucell.nat, 3);
    ModuleIO::CifParser::write(PARAM.globalv.global_out_dir + "STRU.cif",
                               ucell,
                               "# Generated by ABACUS ModuleIO::CifParser",
                               "data_?");
    atype.resize(ucell.nat);
#ifdef __DPMD
    type_map(ucell);
#endif
}

void ESolver_DP::runner(BaseCell& basecell, const int istep)
{
    ModuleBase::TITLE("ESolver_DP", "runner");
    ModuleBase::timer::start("ESolver_DP", "runner");

    if (basecell.kind() == BaseCell::Kind::mdcell)
    {
#ifndef __DPMD
        ModuleBase::WARNING_QUIT("ESolver_DP", "Please recompile with -D__DPMD");
#else
        static_cast<void>(istep);
        MDCell& mdcell = static_cast<MDCell&>(basecell);
        if (!mdcell.has_neighbor_search())
        {
            ModuleBase::WARNING_QUIT("ESolver", "MDCell neighbors must be prepared by the caller before runner().");
        }
        const int nowned_atoms = mdcell.owned_atoms().size();
        const int nghost = mdcell.ghost_atoms().size();
        const int natom = nowned_atoms + nghost;
        if (natom == 0)
        {
            ModuleBase::WARNING_QUIT("ESolver_DP", "MDCell contains no atoms.");
        }

        std::vector<double> cell(9, 0.0);
        cell[0] = mdcell.latvec().e11 * mdcell.lat0() * ModuleBase::BOHR_TO_A;
        cell[1] = mdcell.latvec().e12 * mdcell.lat0() * ModuleBase::BOHR_TO_A;
        cell[2] = mdcell.latvec().e13 * mdcell.lat0() * ModuleBase::BOHR_TO_A;
        cell[3] = mdcell.latvec().e21 * mdcell.lat0() * ModuleBase::BOHR_TO_A;
        cell[4] = mdcell.latvec().e22 * mdcell.lat0() * ModuleBase::BOHR_TO_A;
        cell[5] = mdcell.latvec().e23 * mdcell.lat0() * ModuleBase::BOHR_TO_A;
        cell[6] = mdcell.latvec().e31 * mdcell.lat0() * ModuleBase::BOHR_TO_A;
        cell[7] = mdcell.latvec().e32 * mdcell.lat0() * ModuleBase::BOHR_TO_A;
        cell[8] = mdcell.latvec().e33 * mdcell.lat0() * ModuleBase::BOHR_TO_A;

        const std::vector<LocalAtom>& owned_atoms = mdcell.owned_atoms();
        const std::vector<LocalAtom>& ghost_atoms = mdcell.ghost_atoms();
        std::vector<double> coord(static_cast<std::size_t>(3 * natom), 0.0);
        std::vector<int> local_atype(static_cast<std::size_t>(natom), 0);
        for (int iat = 0; iat < natom; ++iat)
        {
            const LocalAtom& atom = iat < nowned_atoms ? owned_atoms[static_cast<std::size_t>(iat)]
                                                  : ghost_atoms[static_cast<std::size_t>(iat - nowned_atoms)];
            coord[3 * iat] = atom.cart.x * mdcell.lat0() * ModuleBase::BOHR_TO_A;
            coord[3 * iat + 1] = atom.cart.y * mdcell.lat0() * ModuleBase::BOHR_TO_A;
            coord[3 * iat + 2] = atom.cart.z * mdcell.lat0() * ModuleBase::BOHR_TO_A;
            if (atom.type < 0 || static_cast<std::size_t>(atom.type) >= md_type_to_dp_type_.size())
            {
                ModuleBase::WARNING_QUIT("ESolver_DP", "MDCell atom type is outside the DeePMD type map.");
            }
            local_atype[static_cast<std::size_t>(iat)] = md_type_to_dp_type_[static_cast<std::size_t>(atom.type)];
        }

        const int dim_aparam = dp.dim_aparam();
        if (dim_aparam > 0)
        {
            ModuleBase::WARNING_QUIT("ESolver_DP",
                                     "MDCell support does not yet support DeePMD atomic parameters (dim_aparam > 0).");
        }

        const NeighborList& neighbor_list = mdcell.neighbor_search().get_neighbor_list();
        std::vector<int> ilist(static_cast<std::size_t>(nowned_atoms), 0);
        std::vector<int> numneigh(static_cast<std::size_t>(nowned_atoms), 0);
        std::vector<int*> firstneigh(static_cast<std::size_t>(nowned_atoms), NULL);
        for (int iat = 0; iat < nowned_atoms; ++iat)
        {
            ilist[static_cast<std::size_t>(iat)] = iat;
            numneigh[static_cast<std::size_t>(iat)] = neighbor_list.get_numneigh(iat);
            firstneigh[static_cast<std::size_t>(iat)] = const_cast<int*>(neighbor_list.get_firstneigh(iat));
        }
#ifdef __DPMDC
        deepmd::hpp::InputNlist nlist(nowned_atoms,
                                      nowned_atoms > 0 ? &ilist[0] : NULL,
                                      nowned_atoms > 0 ? &numneigh[0] : NULL,
                                      nowned_atoms > 0 ? &firstneigh[0] : NULL);
#else
        deepmd::InputNlist nlist(nowned_atoms,
                                 nowned_atoms > 0 ? &ilist[0] : NULL,
                                 nowned_atoms > 0 ? &numneigh[0] : NULL,
                                 nowned_atoms > 0 ? &firstneigh[0] : NULL);
#endif
        double local_energy = 0.0;
        std::vector<double> force, virial;
        ModuleBase::timer::start("ESolver_DP", "compute");
        dp.compute(local_energy, force, virial, coord, local_atype, cell, nghost, nlist, 0, fparam);
        ModuleBase::timer::end("ESolver_DP", "compute");
        if (force.size() != static_cast<std::size_t>(3 * natom))
        {
            ModuleBase::WARNING_QUIT("ESolver_DP", "DeePMD returned an invalid force array for MDCell.");
        }

        std::vector<LocalAtom>& mutable_owned_atoms = mdcell.owned_atoms();
        std::vector<LocalAtom>& mutable_ghost_atoms = mdcell.ghost_atoms();
        for (int iat = 0; iat < nowned_atoms; ++iat)
        {
            mutable_owned_atoms[static_cast<std::size_t>(iat)].force.set(force[3 * iat], force[3 * iat + 1], force[3 * iat + 2]);
        }
        for (int iat = 0; iat < nghost; ++iat)
        {
            mutable_ghost_atoms[static_cast<std::size_t>(iat)].force.set(force[3 * (nowned_atoms + iat)],
                                                                           force[3 * (nowned_atoms + iat) + 1],
                                                                           force[3 * (nowned_atoms + iat) + 2]);
        }

        if (virial.size() != 9)
        {
            ModuleBase::WARNING_QUIT("ESolver_DP", "DeePMD returned an invalid virial tensor for MDCell.");
        }

        std::array<double, 9> local_virial;
        std::copy(virial.begin(), virial.end(), local_virial.begin());
#ifdef __MPI
        MPI_Allreduce(MPI_IN_PLACE, &local_energy, 1, MPI_DOUBLE, MPI_SUM, mdcell.communicator());
        MPI_Allreduce(MPI_IN_PLACE, local_virial.data(), 9, MPI_DOUBLE, MPI_SUM, mdcell.communicator());
#endif
        const double fact_e = rescaling / ModuleBase::Ry_to_eV;
        const double fact_f = rescaling / (ModuleBase::Ry_to_eV * ModuleBase::ANGSTROM_AU);
        const double fact_v = rescaling / (mdcell.omega() * ModuleBase::Ry_to_eV);
        dp_potential = local_energy * fact_e;
        for (int iat = 0; iat < nowned_atoms; ++iat)
        {
            LocalAtom& atom = mutable_owned_atoms[static_cast<std::size_t>(iat)];
            atom.force *= fact_f;
        }
        for (LocalAtom& atom : mutable_ghost_atoms)
        {
            atom.force *= fact_f;
        }
        for (int i = 0; i < 3; ++i)
            for (int j = 0; j < 3; ++j)
                dp_virial(i, j) = local_virial[static_cast<std::size_t>(3 * i + j)] * fact_v;
#endif
        ModuleBase::timer::end("ESolver_DP", "runner");
        return;
    }

    UnitCell& ucell = static_cast<UnitCell&>(basecell);

    std::vector<double> cell(9, 0.0);
    cell[0] = ucell.latvec.e11 * ucell.lat0_angstrom;
    cell[1] = ucell.latvec.e12 * ucell.lat0_angstrom;
    cell[2] = ucell.latvec.e13 * ucell.lat0_angstrom;
    cell[3] = ucell.latvec.e21 * ucell.lat0_angstrom;
    cell[4] = ucell.latvec.e22 * ucell.lat0_angstrom;
    cell[5] = ucell.latvec.e23 * ucell.lat0_angstrom;
    cell[6] = ucell.latvec.e31 * ucell.lat0_angstrom;
    cell[7] = ucell.latvec.e32 * ucell.lat0_angstrom;
    cell[8] = ucell.latvec.e33 * ucell.lat0_angstrom;

    std::vector<double> coord(3 * ucell.nat, 0.0);
    int iat = 0;
    for (int it = 0; it < ucell.ntype; ++it)
    {
        for (int ia = 0; ia < ucell.atoms[it].na; ++ia)
        {
            coord[3 * iat] = ucell.atoms[it].tau[ia].x * ucell.lat0_angstrom;
            coord[3 * iat + 1] = ucell.atoms[it].tau[ia].y * ucell.lat0_angstrom;
            coord[3 * iat + 2] = ucell.atoms[it].tau[ia].z * ucell.lat0_angstrom;
            iat++;
        }
    }
    assert(ucell.nat == iat);

#ifdef __DPMD
    std::vector<double> f, v;
    dp_potential = 0;
    dp_force.zero_out();
    dp_virial.zero_out();

    dp.compute(dp_potential, f, v, coord, atype, cell, fparam, aparam);

    // rescale the energy, force, and stress
    const double fact_e = rescaling / ModuleBase::Ry_to_eV;
    const double fact_f = rescaling / (ModuleBase::Ry_to_eV * ModuleBase::ANGSTROM_AU);
    const double fact_v = rescaling / (ucell.omega * ModuleBase::Ry_to_eV);

    dp_potential *= fact_e;
    GlobalV::ofs_running << " #TOTAL ENERGY# " << std::setprecision(11) << dp_potential * ModuleBase::Ry_to_eV << " eV"
                         << std::endl;

    for (int i = 0; i < ucell.nat; ++i)
    {
        dp_force(i, 0) = f[3 * i] * fact_f;
        dp_force(i, 1) = f[3 * i + 1] * fact_f;
        dp_force(i, 2) = f[3 * i + 2] * fact_f;
    }

    for (int i = 0; i < 3; ++i)
    {
        for (int j = 0; j < 3; ++j)
        {
            dp_virial(i, j) = v[3 * i + j] * fact_v;
        }
    }
#else
    ModuleBase::WARNING_QUIT("ESolver_DP", "Please recompile with -D__DPMD");
#endif
    ModuleBase::timer::end("ESolver_DP", "runner");
}

double ESolver_DP::cal_energy()
{
    return dp_potential;
}

void ESolver_DP::cal_force(BaseCell& basecell, ModuleBase::matrix& force)
{
    if (basecell.kind() == BaseCell::Kind::mdcell)
    {
        const MDCell& mdcell = static_cast<const MDCell&>(basecell);
        force.create(mdcell.owned_atoms().size(), 3);
        for (int iat = 0; iat < mdcell.owned_atoms().size(); ++iat)
        {
            const LocalAtom& atom = mdcell.owned_atoms()[static_cast<std::size_t>(iat)];
            force(iat, 0) = atom.force.x;
            force(iat, 1) = atom.force.y;
            force(iat, 2) = atom.force.z;
        }
        return;
    }
    force = dp_force;
    ModuleIO::print_force(GlobalV::ofs_running,
                          static_cast<UnitCell&>(basecell),
                          "TOTAL-FORCE (eV/Angstrom)", force, false);
}

void ESolver_DP::cal_stress(BaseCell& basecell, ModuleBase::matrix& stress)
{
    stress = dp_virial;

    if (basecell.kind() == BaseCell::Kind::unitcell)
    {
        ModuleIO::print_stress("TOTAL-STRESS", stress, true, false, GlobalV::ofs_running);
    }
    else
    {
#ifdef __MPI
        if (static_cast<MDCell&>(basecell).mpi_rank() == 0)
#endif
        {
            ModuleIO::print_stress("TOTAL-STRESS", stress, true, false, GlobalV::ofs_running);
        }
    }

    // external stress
    double unit_transform = ModuleBase::RYDBERG_SI / pow(ModuleBase::BOHR_RADIUS_SI, 3) * 1.0e-8;
    double external_stress[3] = {this->inp_->press1, this->inp_->press2, this->inp_->press3};
    for (int i = 0; i < 3; i++)
    {
        stress(i, i) -= external_stress[i] / unit_transform;
    }
}

void ESolver_DP::after_all_runners(BaseCell& basecell)
{
    static_cast<void>(basecell);

    GlobalV::ofs_running << "\n --------------------------------------------" << std::endl;
    GlobalV::ofs_running << std::setprecision(16);
    GlobalV::ofs_running << " !FINAL_ETOT_IS " << dp_potential * ModuleBase::Ry_to_eV << " eV" << std::endl;
    GlobalV::ofs_running << " --------------------------------------------\n\n" << std::endl;
}

#ifdef __DPMD
void ESolver_DP::type_map(const UnitCell& ucell)
{
    std::vector<std::string> type_labels(static_cast<std::size_t>(ucell.ntype));
    for (int it = 0; it < ucell.ntype; ++it)
    {
        type_labels[static_cast<std::size_t>(it)] = ucell.atoms[it].label;
    }
    initialize_type_map_(type_labels);

    int iat = 0;
    for (int it = 0; it < ucell.ntype; ++it)
    {
        for (int ia = 0; ia < ucell.atoms[it].na; ++ia)
        {
            atype[static_cast<std::size_t>(iat++)] = md_type_to_dp_type_[static_cast<std::size_t>(it)];
        }
    }
    assert(ucell.nat == iat);
}

void ESolver_DP::initialize_type_map_(const std::vector<std::string>& type_labels)
{
    std::string type = "";
    dp.get_type_map(type);
    std::stringstream ss(type);
    std::unordered_map<std::string, int> label;
    std::string temp;
    int index = 0;
    while (ss >> temp)
    {
        label[temp] = index;
        index++;
    }

    std::cout << "\n type map of model file " << dp_file << " " << std::endl;
    std::cout << " ----------------------------------------------------------------";
    int count = 0;
    for (auto it = label.begin(); it != label.end(); ++it)
    {
        if (count % 5 == 0)
        {
            std::cout << std::endl;
            std::cout << "  ";
        }
        count++;
        temp = it->first + ": " + std::to_string(it->second);
        std::cout << std::left << std::setw(10) << temp;
    }
    std::cout << "\n -----------------------------------------------------------------" << std::endl;

    md_type_to_dp_type_.resize(type_labels.size());
    for (std::size_t it = 0; it < type_labels.size(); ++it)
    {
        const std::unordered_map<std::string, int>::const_iterator found = label.find(type_labels[it]);
        if (found == label.end())
        {
            ModuleBase::WARNING_QUIT("ESolver_DP",
                                     "The label " + type_labels[it] + " is not found in the type map.");
        }
        md_type_to_dp_type_[it] = found->second;
    }
}
#endif
