#
# The ABACUS-cell module
#

VERSION= ABACUS-cell
HEADERS= *.h

OBJS_MAIN=input.o\

OBJS_IO=output.o\

OBJS_PW=magnetism.o\

OBJS_PARALELL=parallel_reduce.o\
parallel_common.o\
parallel_global.o\

OBJS_BASE=math_integral.o\
math_sphbes.o\
math_polyint.o\
math_ylmreal.o\
ylm.o\
memory.o\
matrix3.o\
matrix.o\
intarray.o\
sph_bessel.o\
sph_bessel_recursive-d1.o\
sph_bessel_recursive-d2.o\
complexarray.o\
complexmatrix.o\
timer.o\
realarray.o\
global_file.o\
global_function.o\
global_variable.o\
tool_title.o\
tool_quit.o\
tool_check.o\
mathzone_add1.o\

OBJS_CELL=pseudo_nc.o\
atom_spec.o\
atom_pseudo.o\
read_pp.o\
read_pp_upf100.o\
read_pp_upf201.o\
read_pp_vwr.o\
read_pp_blps.o\
unitcell.o\
unitcell_pseudo.o\
read_atoms.o\
read_cell_pseudopots.o\
cell_unittest.o\

OBJS_ORB=ORB_control.o\
ORB_read.o\
ORB_atomic.o\
ORB_atomic_lm.o\
ORB_nonlocal.o\
ORB_nonlocal_lm.o\
ORB_gaunt_table.o\
ORB_table_beta.o\
ORB_table_phi.o\
ORB_table_alpha.o\
ORB_gen_tables.o\
ORB_unittest.o\

OBJS_NEIGHBOR=sltk_adjacent_set.o\
sltk_atom_arrange.o\
sltk_atom.o\
sltk_atom_input.o\
sltk_grid.o\
sltk_grid_driver.o
