#ifndef STO_HCHI_H
#define STO_HCHI_H

//-----------------------------------------------------
// h * chi
// chi: stochastic wave functions
//
// h: the normalized Hamiltonian matrix, which equals to (H - E\bar) / \DeltaE
// where H is decomposed into the electron kinetic, effective potential V(r),
// and the non-local pseudopotentials.
// The effective potential = Local pseudopotential +
// Hartree potential + Exchange-correlation potential
//------------------------------------------------------
class Stochastic_hchi
{

	public:

    // constructor and deconstructor
    Stochastic_hchi();
    ~Stochastic_hchi();

	static void init();



	double Emin;
	double Emax;

	void hchi_real(
		complex<double> *wfin, 
		complex<double> *wfout, 
		const int m = 1); //wfin & wfout are wavefunctions in real space
	
	void orthogonal_to_psi_reciprocal(
		complex<double>* wfin, 
		complex<double> *wfout, 
		const int& ikk); //wfin & wfout are wavefunctions in reciprocal space

	void hchi_reciprocal(
		complex<double> *wfin, 
		complex<double> *wfout, 
		const int m = 1); //wfin & wfout are wavefunctions in reciprocal space

	public:
	
	int current_ik = 0;

	// chi should be orthogonal to psi (generated by diaganolization methods,
	// such as CG)

};

#endif// Eelectrons_hchi
