#
# The ABACUS-neighbor module
#

VERSION= ABACUS-neighbor
HEADERS= *.h

OBJS_BASE=

OBJS_ADJACENT=sltk_adjacent_set.o\
sltk_atom_arrange.o\
sltk_atom.o\
sltk_atom_input.o\
sltk_grid.o\
sltk_grid_driver.o

