FROM ghcr.io/deepmodeling/abacus-development-kit:gnu

RUN wget https://developer.download.nvidia.com/compute/cuda/11.7.0/local_installers/cuda_11.7.0_515.43.04_linux.run --no-check-certificate --quiet \
	&& sh cuda_11.7.0_515.43.04_linux.run --toolkit --silent \
	&& rm cuda_11.7.0_515.43.04_linux.run
ENV PATH=/usr/local/cuda/bin:$PATH
