#
# The ABACUS-neighbor module
#

VERSION= ABACUS-neighbor
HEADERS= *.h

OBJS_BASE=tool_quit.o\
tool_title.o\
timer.o\
global_variable.o\
matrix.o\
matrix3.o\
memory.o\

OBJS_NEIGHBOR=sltk_adjacent_set.o\
sltk_atom_arrange.o\
sltk_atom.o\
sltk_atom_input.o\
sltk_grid.o\
sltk_grid_driver.o

