/**
 * @file read_pp.h
 * @brief Pseudopot_upf class for reading pseudopotential files.
 */
#ifndef PSEUDOPOT_UPF_H
#define PSEUDOPOT_UPF_H

#include <string>

#include "atom_pseudo.h"
#include "source_base/matrix.h"
#include "source_base/realarray.h"

class AtomPseudoTest;
class AtomSpecTest;
class NCPPTest;
class ReadPPTest;

/**
 * @brief Pseudopot_upf class for reading pseudopotential files.
 *
 * This class handles reading various pseudopotential formats (UPF, VWR, BLPS).
 * It supports UPF format versions including UPF201.
 */
class Pseudopot_upf
{
    /// @brief the unit tests drive the private format readers and the
    /// complete_default_* helpers directly; see source_cell/test/
    friend class AtomPseudoTest;
    friend class AtomSpecTest;
    friend class NCPPTest;
    friend class ReadPPTest;

public:
    /// PP_INFO
    /// PP_HEADER
    /// PP_MESH
    /// PP_NLCC
    /// PP_LOCAL
    /// PP_NONLOCAL
    /// PP_PSWFC
    /// PP_PSRHOATOM
    /// addinfo

    /**
     * @brief Default constructor.
     */
    Pseudopot_upf();

    /**
     * @brief Destructor.
     */
    ~Pseudopot_upf();

    std::string relativistic; ///< relativistic: no, scalar, full
    int lmax_rho;             ///< maximum angular momentum component in rho (should be 2*lmax)
    double xmin;              ///< the minimum x of the linear mesh
    double rmax;              ///< the maximum radius of the mesh
    double zmesh;             ///< the nuclear charge used for mesh
    double dx;                ///< the deltax of the linear mesh
                              ///< The radial grid is: r(i+1) = exp(xmin+i*dx)/zed  a.u.
    int lloc;                 ///< L of channel used to generate local potential
                              ///<   (if < 0 it was generated by smoothing AE potential)
    bool q_with_l;            ///< if .true. qfunc is pseudized in
    int nqf;                  ///< number of Q coefficients

    /// Dynamic arrays
    bool coulomb_potential = false;  ///< coulomb potential : z/r
    ModuleBase::matrix chi;          ///< chi(nwfc,mesh) atomic wavefcts
    std::vector<int> kbeta = {};            ///< kbeta(nbeta):number of mesh points for projector i (must be .le. mesh )
    std::vector<std::string> els_beta = {}; ///< els_beta(nwfc):label for the beta
    std::vector<int> nchi = {};             ///< nchi(nwfc) value of pseudo-n for wavefcts
    std::vector<double> epseu = {};         ///< epseu(nwfc) pseudo one-particle energy
    std::vector<double> rcut_chi = {};      ///< rcut_chi(nwfc) cutoff inner radius
    std::vector<double> rcutus_chi = {};    ///< rcutus_chi(nwfc) ultrasoft outer radius
    std::vector<double> rinner = {};        ///< rinner(2*lmax+1) r_L
    ModuleBase::matrix qfunc;        ///< qfunc(nbeta*(nbeta+1)/2,mesh) Q_{mu,nu}(|r|) function for |r|> r_L
    ModuleBase::realArray qfcoef;    ///< qfcoef(nbeta,nbeta,2*lmax+1,nqf) coefficients for Q for |r|<r_L
    std::vector<double> rcut = {};   ///< cut-off radius(nbeta)
    std::vector<double> rcutus = {}; ///< ultrasoft cut-off radius (nbeta)

    int nd; ///< nl_5 // Number of nonzero Dij

    /// VWR format
    int spd_loc; ///< s,p,d local component
    int iTB_s;   ///< TB s orbital index
    int iTB_p;   ///< TB p orbital index
    int iTB_d;   ///< TB d orbital index

    /**
     * @brief Initialize pseudopotential reader.
     *
     * @param fn filename
     * @param type pseudopotential type (output)
     * @param pp atom pseudopotential object (output)
     * @return error code
     */
    int init_pseudo_reader(const std::string& fn, std::string& type, Atom_pseudo& pp);

    /**
     * @brief Print pseudopotential information.
     *
     * @param ofs output file stream
     * @param pp atom pseudopotential object
     */
    void print_pseudo_upf(std::ofstream& ofs, Atom_pseudo& pp);

    /**
     * @brief Average pseudopotential.
     *
     * @param lambda averaging parameter
     * @param pp atom pseudopotential object
     * @param lspinorb whether spin-orbit is enabled
     * @return error code
     */
    int average_p(const double& lambda, Atom_pseudo& pp, const bool lspinorb);

    /**
     * @brief Set empty element for BSSE.
     *
     * @param pp atom pseudopotential object
     * @note Peize Lin add for bsse 2022.04.07
     */
    void set_empty_element(Atom_pseudo& pp);

    /**
     * @brief Set UPF Q function.
     *
     * @param pp atom pseudopotential object
     * @note liuyu add 2023-09-21
     */
    void set_upf_q(Atom_pseudo& pp);

    /**
     * @brief Complete default values.
     *
     * @param pp atom pseudopotential object
     * @param pseudo_rcut pseudo cut-off radius
     */
    void complete_default(Atom_pseudo& pp, const double pseudo_rcut);

  private:
    bool mesh_changed = false; ///< if the mesh is even, it will be changed to odd

    /**
     * @brief Skip the last number if the mesh is even.
     *
     * @param ifs input file stream
     * @param mesh_changed whether mesh was changed
     */
    void skip_number(std::ifstream& ifs, bool mesh_changed);

    /**
     * @brief Read UPF format pseudopotential.
     *
     * @param ifs input file stream
     * @param pp atom pseudopotential object
     * @return error code
     */
    int read_pseudo_upf(std::ifstream& ifs, Atom_pseudo& pp);

    /**
     * @brief Read VWR format pseudopotential.
     *
     * @param ifs input file stream
     * @param pp atom pseudopotential object
     * @return error code
     */
    int read_pseudo_vwr(std::ifstream& ifs, Atom_pseudo& pp);

    /**
     * @brief Read BLPS format pseudopotential.
     *
     * @param ifs input file stream
     * @param pp atom pseudopotential object
     * @return error code
     * @note sunliang added 2021.07.08
     */
    int read_pseudo_blps(std::ifstream& ifs, Atom_pseudo& pp);

    /**
     * @brief Read pseudopotential header.
     *
     * @param ifs input file stream
     * @param pp atom pseudopotential object
     */
    void read_pseudo_header(std::ifstream& ifs, Atom_pseudo& pp);

    /**
     * @brief Read pseudopotential mesh.
     *
     * @param ifs input file stream
     * @param pp atom pseudopotential object
     */
    void read_pseudo_mesh(std::ifstream& ifs, Atom_pseudo& pp);

    /**
     * @brief Read pseudopotential NLCC.
     *
     * @param ifs input file stream
     * @param pp atom pseudopotential object
     */
    void read_pseudo_nlcc(std::ifstream& ifs, Atom_pseudo& pp);

    /**
     * @brief Read pseudopotential local potential.
     *
     * @param ifs input file stream
     * @param pp atom pseudopotential object
     */
    void read_pseudo_local(std::ifstream& ifs, Atom_pseudo& pp);

    /**
     * @brief Read pseudopotential non-local potential.
     *
     * @param ifs input file stream
     * @param pp atom pseudopotential object
     */
    void read_pseudo_nl(std::ifstream& ifs, Atom_pseudo& pp);

    /**
     * @brief Read pseudopotential pseudo wavefunctions.
     *
     * @param ifs input file stream
     * @param pp atom pseudopotential object
     */
    void read_pseudo_pswfc(std::ifstream& ifs, Atom_pseudo& pp);

    /**
     * @brief Read pseudopotential atomic charge density.
     *
     * @param ifs input file stream
     * @param pp atom pseudopotential object
     */
    void read_pseudo_rhoatom(std::ifstream& ifs, Atom_pseudo& pp);

    /**
     * @brief Read pseudopotential additional info.
     *
     * @param ifs input file stream
     * @param pp atom pseudopotential object
     */
    void read_pseudo_addinfo(std::ifstream& ifs, Atom_pseudo& pp);

    /**
     * @brief Read pseudopotential spin-orbit coupling.
     *
     * @param ifs input file stream
     * @param pp atom pseudopotential object
     */
    void read_pseudo_so(std::ifstream& ifs, Atom_pseudo& pp);

    /// UPF201 format
    /**
     * @brief Read UPF201 format pseudopotential.
     *
     * @param ifs input file stream
     * @param pp atom pseudopotential object
     * @return error code
     */
    int read_pseudo_upf201(std::ifstream& ifs, Atom_pseudo& pp);

    /**
     * @brief Read UPF201 header.
     *
     * @param ifs input file stream
     * @param pp atom pseudopotential object
     */
    void read_pseudo_upf201_header(std::ifstream& ifs, Atom_pseudo& pp);

    /**
     * @brief Read UPF201 mesh.
     *
     * @param ifs input file stream
     * @param pp atom pseudopotential object
     */
    void read_pseudo_upf201_mesh(std::ifstream& ifs, Atom_pseudo& pp);

    /**
     * @brief Read UPF201 non-local potential.
     *
     * @param ifs input file stream
     * @param pp atom pseudopotential object
     */
    void read_pseudo_upf201_nonlocal(std::ifstream& ifs, Atom_pseudo& pp);

    /**
     * @brief Read UPF201 pseudo wavefunctions.
     *
     * @param ifs input file stream
     * @param pp atom pseudopotential object
     */
    void read_pseudo_upf201_pswfc(std::ifstream& ifs, Atom_pseudo& pp);

    /**
     * @brief Read UPF201 spin-orbit coupling.
     *
     * @param ifs input file stream
     * @param pp atom pseudopotential object
     */
    void read_pseudo_upf201_so(std::ifstream& ifs, Atom_pseudo& pp);

    /**
     * @brief Get name-value pair from input stream.
     *
     * @param ifs input file stream
     * @param ival integer value (output)
     * @param sval1 string value 1 (output)
     * @param sval2 string value 2 (output)
     */
    void getnameval(std::ifstream&, int&, std::string*, std::string*);

    // complete default
    // void complete_default(Atom_pseudo& pp);
    void complete_default_atom(Atom_pseudo& pp, const double pseudo_rcut);
    void complete_default_vl(Atom_pseudo& pp);
};

/**
 * @brief Helpers that the pseudopotential reader uses but that hold no state.
 *
 * These were private members of Pseudopot_upf, which meant their unit tests had
 * to reach past access control to call them. None of them touches `this`: they
 * work entirely on their arguments, so they are plain functions and are
 * declared here as such -- publicly callable and directly testable, without
 * widening the interface of Pseudopot_upf.
 */
namespace pseudopot
{

/// @brief Set pseudopotential type based on the file's header line.
int set_pseudo_type(const std::string& fn, std::string& type);

/// @brief Remove every tab and space from a string, in place.
std::string& trim(std::string& in_str);

/// @brief Compute the Q function from its polynomial expansion (r < rinner).
/// @param nqf number of polynomial coefficients
/// @param mesh number of mesh points
/// @param l angular momentum
/// @param n additional exponent, result is multiplied by r^n
/// @param qfcoef polynomial coefficients
/// @param r radial mesh
/// @param rho output: r^n * Q(r)
void setqfnew(const int& nqf,
              const int& mesh,
              const int& l,
              const int& n,
              const double* qfcoef,
              const double* r,
              double* rho);

/// @brief Fill in the header-level defaults of an Atom_pseudo.
void complete_default_h(Atom_pseudo& pp);

} // namespace pseudopot

#endif //pseudopot_upf class
