/**
 * @file reciprocal_grid.h
 * @brief Abstract base class for reciprocal-space point grids.
 * @note Extracted from K_Vectors (2026-08-14; the intermediate KVectorUtils
 *       shim has since been folded back into the member functions) so that
 *       both k-points (K_Vectors) and q-points (QList) share the common
 *       spin-free functionality: mesh generation, coordinate conversion,
 *       weight normalization, printing and star (IBZ) reduction.
 */
#ifndef RECIPROCAL_GRID_H
#define RECIPROCAL_GRID_H

#include "source_base/matrix3.h"
#include "source_base/vector3.h"
#include <fstream>
#include <string>
#include <vector>

class UnitCell;
namespace ModuleSymmetry
{
class Symmetry;
}

namespace ModuleCell
{

/**
 * @brief Fold a point into (-0.5, 0.5] in direct coordinates.
 *
 * Uses the epsilon-shifted fmod convention shared with the symmetry
 * checker, and zeroes components below the epsilon tolerance.
 *
 * @param kvec    point to fold in place
 * @param epsilon symmetry tolerance
 */
void restrict_kpt(ModuleBase::Vector3<double>& kvec, double epsilon);

/**
 * @brief Abstract base class shared by K_Vectors (electrons) and QList (phonons).
 *
 * This base class is deliberately spin-free and irrep-free:
 * - spin expansion (isk, nspin doubling) is implemented in K_Vectors;
 * - irreducible-representation analysis is implemented in QList.
 */
class ReciprocalGrid
{
  public:
    /// Cartesian coordinates of the points, in unit of 2*pi/lat0.
    std::vector<ModuleBase::Vector3<double>> kvec_c;
    /// Direct coordinates of the points.
    std::vector<ModuleBase::Vector3<double>> kvec_d;
    /// Cartesian coordinates of the full (unreduced) mesh, in unit of 2*pi/lat0.
    std::vector<ModuleBase::Vector3<double>> kvec_c_full;
    /// Weight of each point.
    std::vector<double> wk;
    /// Number of plane waves for each point (filled by the PW basis).
    std::vector<int> ngk;
    /// Monkhorst-Pack grid dimensions.
    int nmp[3] = {0, 0, 0};
    /// Index of the k-line segment each point belongs to.
    std::vector<int> kl_segids;

    /// Whether the Cartesian coordinates have been computed.
    bool kc_done = false;
    /// Whether the direct coordinates have been computed.
    bool kd_done = false;

    /// Number of points in the current pool (spin-free view).
    int nks = 0;
    /// Total number of (symmetry-reduced) points, INCLUDING spin multiplicity
    /// (i.e. nkstot = nkstot_nospin * spin_mult after K_Vectors::set_kup_and_kdw).
    int nkstot = 0;
    /// Total number of physical k-points before symmetry reduction,
    /// WITHOUT spin multiplicity. EXX/RI/LR code relies on this convention
    /// (see e.g. ri_2d_comm.hpp: ik_full + is_k * nkstot_nospin).
    int nkstot_nospin = 0;

    ReciprocalGrid() = default;
    virtual ~ReciprocalGrid() = default;
    ReciprocalGrid& operator=(const ReciprocalGrid&) = default;
    ReciprocalGrid& operator=(ReciprocalGrid&&) = default;

    /**
     * @brief Resize the point-related containers.
     *
     * @param kpoint_number new number of points
     */
    virtual void renew(const int& kpoint_number);

    /// @brief Coordinate of a point generated by the Monkhorst-Pack scheme.
    double Monkhorst_Pack_formula(const int& k_type, const double& offset, const int& n, const int& dim);

    /// @brief Generate a Monkhorst-Pack mesh.
    void Monkhorst_Pack(const int* nmp_in, const double* koffset_in, const int k_type);

    /// @brief Convert direct to Cartesian coordinates.
    void kvec_d2c(const ModuleBase::Matrix3& reciprocal_vec);

    /// @brief Convert Cartesian to direct coordinates.
    void kvec_c2d(const ModuleBase::Matrix3& latvec);

    /**
     * @brief Set both the direct and Cartesian coordinates, and print the table.
     *
     * @param G reciprocal lattice matrix
     * @param R real space lattice matrix
     * @param skpt output string holding the point table
     * @param ofs_running running-log stream
     */
    void set_both_kvec(const ModuleBase::Matrix3& G,
                       const ModuleBase::Matrix3& R,
                       std::string& skpt,
                       std::ofstream& ofs_running,
                       std::ofstream& ofs_warning);

    /// @brief Normalize the weights so that they sum to the spin degeneracy.
    void normalize_wk(const int& degspin);

    /// @brief Print the points in both Cartesian and direct coordinates.
    void print_klists(std::ofstream& ofs) const;

    /**
     * @brief Star (IBZ) reduction primitive shared by k-points and q-points.
     *
     * Rotates every point by each operation in `rot_ops`, folds equivalent
     * points together and accumulates their weights. The rotation matrices in
     * the k-lattice (Monkhorst-Pack) frame are provided in `kkmatrix` when
     * `is_mp` is true; the k-lattice basis is `k_lattice`.
     *
     * @param rot_ops    rotation matrices in the reciprocal-space frame
     * @param nrotkm     number of rotation operations
     * @param G          reciprocal lattice matrix
     * @param k_lattice  k-lattice basis matrix (valid when is_mp)
     * @param kkmatrix   rotation matrices in the k-lattice frame (valid when is_mp)
     * @param epsilon    symmetry tolerance used by restrict/equivalence checks
     * @param vec_ibz    output: irreducible points
     * @param wk_ibz     output: weight of each irreducible point
     * @param ibz_index  output: mapping point index -> irreducible index
     * @param ibz2bz     output: origin (full-mesh) index of each irreducible point
     */
    void reduce_ibz(const ModuleBase::Matrix3* rot_ops,
                    int nrotkm,
                    const ModuleBase::Matrix3& G,
                    const ModuleBase::Matrix3& k_lattice,
                    const ModuleBase::Matrix3* kkmatrix,
                    double epsilon,
                    std::vector<ModuleBase::Vector3<double>>& vec_ibz,
                    std::vector<double>& wk_ibz,
                    std::vector<int>& ibz_index,
                    std::vector<int>& ibz2bz);

    /**
     * @brief Reduce this grid according to symmetry operations.
     *
     * Pure virtual: implemented by K_Vectors (electron IBZ, including the
     * magnetic/time-reversal handling) and by QList (q-point star reduction
     * plus irreducible-representation analysis).
     */
    virtual void reduce_by_symmetry(const UnitCell& ucell,
                                    const ModuleSymmetry::Symmetry& symm,
                                    bool use_symm,
                                    std::string& skpt,
                                    bool& match,
                                    const int my_rank,
                                    std::ofstream& ofs_running) = 0;

    /// Whether this is a Monkhorst-Pack grid.
    bool is_mp = false;
    /// Total number of points read from a point-list file (0 = auto mesh).
    int k_nkstot = 0;
    /// Type keyword of the point-list file.
    std::string k_kword;

  protected:
    /// @brief Spin-like multiplicity used by renew() (1 for q-points).
    virtual int spin_factor() const { return 1; }

    /**
     * @brief Build the reciprocal-space point-group operations for star reduction.
     *
     * Determines the Bravais lattice of the reciprocal lattice (and of the
     * k-lattice for Monkhorst-Pack meshes), checks its compatibility with the
     * real-space lattice, constructs the point-group operations, and verifies
     * that every Symmetry::kgmatrix entry belongs to that group.
     *
     * @param ucell    unit cell
     * @param symm     symmetry of the system
     * @param use_symm whether symmetry reduction is enabled
     * @param k_vec    output: k-lattice basis matrix (valid when is_mp)
     * @param kgmatrix output: rotation operations (capacity at least 96)
     * @param nrotkm   output: number of operations written into kgmatrix
     *                 (0 means no reduction is possible)
     * @return false if the reciprocal lattice is incompatible with the
     *         real-space lattice (the caller should then set match to false)
     */
    bool build_star_ops(const UnitCell& ucell,
                        const ModuleSymmetry::Symmetry& symm,
                        bool use_symm,
                        ModuleBase::Matrix3& k_vec,
                        std::vector<ModuleBase::Matrix3>& kgmatrix,
                        int& nrotkm) const;
};

} // namespace ModuleCell

#endif // RECIPROCAL_GRID_H
