name: Software Enhancements
description: Suggest an idea to make ABACUS more robust and organized
labels: Refactor
assignees: 
  - caic99

body:
- type: textarea
  attributes:
    label: Describe Current Status and Possible Solution
    description: |
      A clear and concise description of why this enhancement is important. 
      Describing the current situation of ABACUS is preferred.
      If you have some ideas about how to achieve it, please feel free to comment.
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional Context
    description: |
      Add any other context or screenshots about the enhancement here.

- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!
