list(APPEND objects
    elecstate.cpp
    init_scf.cpp
    estate_e_terms.cpp
    elecstate_energy.cpp
    elecstate_exx.cpp
    elecstate_print.cpp
    elecstate_tools.cpp
    elecstate_pw.cpp
    uspp_density.cpp
    elecstate_pw_sdft.cpp
    elecstate_pw_cal_tau.cpp
    makov_payne.cpp
    module_pot/gatefield.cpp
    module_pot/efield.cpp
    module_pot/h_hartree_pw.cpp
    module_pot/h_tddft_pw.cpp
    module_pot/pot_xc.cpp
    module_pot/pot_local.cpp
    module_pot/potential_new.cpp
    module_pot/potential_types.cpp
    module_pot/pot_ml_exx.cpp
    module_pot/pot_ml_exx_label.cpp
    module_pot/pot_sep.cpp
    module_pot/pot_xc_fdm.cpp
    module_pot/pot_cosikr.cpp
    module_pot/td_field.cpp
    module_pot/td_field_profiles.cpp
    module_pot/td_field_manager.cpp
    module_charge/chgmixing.cpp
    module_charge/gint_prec_ctrl.cpp
    module_charge/charge.cpp
    module_charge/charge_init.cpp
    module_charge/charge_mpi.cpp
    module_charge/charge_extra.cpp
    module_charge/charge_mixing.cpp
    module_charge/charge_mixing_dmr.cpp
    module_charge/mix_resid.cpp
    module_charge/mix_precond.cpp
    module_charge/charge_mixing_rho.cpp
    module_charge/charge_mixing_uspp.cpp
    module_charge/symm_rho.cpp
    module_charge/symm_rhog.cpp
    rhog_io.cpp
    write_elecstat_pot.cpp
    write_init.cpp
    fp_energy.cpp
    occupy.cpp
    occ_matrix.cpp
    occ_mixer.cpp
    param_update.cpp
    setup_estate_pw.cpp
    update_pot.cpp
)

if(ENABLE_LCAO)
  list(APPEND objects
      elecstate_lcao.cpp
      module_dm/init_dm.cpp
      module_dm/density_matrix.cpp
      module_dm/density_matrix_io.cpp
      module_dm/cal_dm_psi.cpp
      module_dm/cal_edm_tddft.cpp
  )
endif()

add_library(
    elecstate
    OBJECT
    ${objects}
)

if(ENABLE_COVERAGE)
  add_coverage(elecstate)
endif()

if(BUILD_TESTING)
  if(ENABLE_MPI)
    add_subdirectory(test)
  endif()
endif()

if(ENABLE_LCAO)
  add_subdirectory(module_dm)
endif()
