include Makefile.vars

#==========================
# LIBS and INCLUDES
#==========================
LIBS = -lifcore -lm -lpthread 

INCLUDES = -I. -Icommands 

#==========================
# OPTIMIZE OPTIONS
#==========================
OPTS     = ${INCLUDES} -Ofast -std=c++11 -simd -march=native -m64 -Werror -Wall -pedantic -g
#OPTS_MPI = -cxx=${CPLUSPLUS}
