CPLUSPLUS      = icpc

CPLUSPLUS_MPI  = mpiicpc

#LAPACK_LIB_DIR = /public/intel2017/compilers_and_libraries_2017.1.132/linux/mkl/lib/intel64
LAPACK_LIB_DIR = $(MKLROOT)/lib/intel64

#FFTW_DIR       = /public/udata/xiaohui/software/fftw2
FFTW_DIR       =/opt/fftw/3.3.6-p12/intel/2017.update4

#BOOST_DIR      = /public/udata/xiaohui/software/boost_1_39_0
BOOST_DIR      = /opt/boost/1.64.0

#ELPA_LIB_DIR   = /public/udata/xiaohui/ELPA-2016.05.004/lib
ELPA_LIB_DIR   = /opt/elpa/intel_2017_update4/lib
