#---------------------------------------------
# FFTW directories
#---------------------------------------------
FFTW_INCLUDE=/usr/include
FFTW_LIB_DIR=/usr/lib64
#---------------------------------------------
# BOOST directories
#---------------------------------------------
BOOST_INCLUDE=/usr/include/boost
BOOST_LIB_DIR=/usr/lib64
#---------------------------------------------
# LAPACK/BLAS directories
#---------------------------------------------
#---------------------------------------------
# LAPACK/BLAS directories
#---------------------------------------------
BLAS_LAPACK_LIB=${MKLROOT}/lib/intel64/libmkl_scalapack_lp64.a -Wl,--start-group ${MKLROOT}/lib/intel64/libmkl_intel_lp64.a ${MKLROOT}/lib/intel64/libmkl_core.a ${MKLROOT}/lib/intel64/libmkl_sequential.a ${MKLROOT}/lib/intel64/libmkl_blacs_intelmpi_lp64.a -Wl,--end-group -lpthread -lm
# ELPA root directory, may be changed if necessary
ELPA=/opt/elpa
ELPA_LIB=${ELPA}/lib
#ELPA_INCLUDE=${ELPA}/include/elpa-2016.05.004

#---------------------------------------------
# All libraries
#---------------------------------------------
LIBS = -L${FFTW_LIB_DIR} -L${ELPA_LIB} -L${BOOST_LIB_DIR} -lfftw -lelpa -lifcore -qopenmp ${BLAS_LAPACK_LIB}

#---------------------------------------------
# Compiler flags for all compilers
#---------------------------------------------
OPTS = -I. -Icommands -I${BOOST_INCLUDE} -I${FFTW_INCLUDE} -Ofast -xHost -diag-disable=858 -std=c++11
#OPTS = -I. -Icommands -I${BOOST_INCLUDE} -I${FFTW_INCLUDE} -ipo -Ofast -xHost -diag-disable=858 -std=c++11

#---------------------------------------------
# C++ compiler and options
#---------------------------------------------
CPLUSPLUS = mpiicc
CPLUSPLUS_MPI = mpiicc
