CPLUSPLUS      = icpc
CPLUSPLUS_MPI  = mpiicpc
BOOST_DIR      = /home/linpz/software/boost_1_66_0
LAPACK_DIR     = /opt/intel/mkl
FFTW_DIR       = /home/linpz/software/fftw-3.3.8
ELPA_DIR       = /home/linpz/software/elpa-2016.05.004
LIBXC_DIR      = /home/linpz/software/libxc-4.0.4
