CPLUSPLUS      = /public/intel2017/bin/icpc
CPLUSPLUS_MPI  = /public/intel2017/impi/2017.1.132/intel64/bin/mpiicpc
#LAPACK_LIB_DIR = /public/intel/mkl/lib/intel64
LAPACK_LIB_DIR = /public/intel2017/compilers_and_libraries_2017.1.132/linux/mkl/lib/intel64
FFTW_DIR       = /public/udata/xiaohui/software/fftw2
BOOST_DIR      = /public/udata/xiaohui/software/boost_1_39_0
#ELPA_LIB_DIR   = /public/udata/xiaohui/ELPA-2016.05.004/lib
ELPA_LIB_DIR   = /public/udata/jingan/app/elpa_test/lib
