#
# The ABACUS-deepks module
#

VERSION= ABACUS-deepks
HEADERS= *.h

OBJS_MAIN=klist_1.o\
parallel_orbitals.o\
deepks_basic.o\
deepks_force.o\
deepks_iterate.o\
deepks_vdelta.o\
deepks_pdm.o\
deepks_phialpha.o\
LCAO_deepks.o\
LCAO_deepks_io.o\

OBJS_IO=output.o\

OBJS_PW=magnetism.o\
soc.o\

OBJS_BASE=math_integral.o\
math_sphbes.o\
math_polyint.o\
math_ylmreal.o\
ylm.o\
memory_recorder.o\
matrix3.o\
matrix.o\
intarray.o\
sph_bessel.o\
sph_bessel_recursive-d1.o\
sph_bessel_recursive-d2.o\
complexarray.o\
complexmatrix.o\
timer.o\
realarray.o\
global_file.o\
global_function.o\
global_variable.o\
tool_title.o\
tool_quit.o\
tool_check.o\
mathzone_add1.o\

OBJS_CELL=pseudo.o\
atom_spec.o\
atom_pseudo.o\
read_pp.o\
read_pp_complete.o\
read_pp_upf100.o\
read_pp_upf201.o\
read_pp_vwr.o\
read_pp_blps.o\
unitcell.o\
check_atomic_stru.o\
read_atoms.o\
read_atoms_helper.o\
read_cell_pseudopots.o\
setup_nonlocal.o

OBJS_ORB=ORB_read.o\
ORB_atomic.o\
ORB_atomic_lm.o\
ORB_nonlocal.o\
ORB_nonlocal_lm.o\
ORB_gaunt_table.o\

OBJS_NEIGHBOR=sltk_atom_arrange.o\
sltk_atom.o\
sltk_grid.o\
sltk_grid_driver.o

OBJS_ELECSTATE=read_pseudo.o\
cal_nelec_nband.o\