# The ABACUS-CMD module
#

VERSION= ABACUS-CMD
HEADERS= *.h

OBJS_MAIN=input.o\

OBJS_MD=MD_basic.o\
MD_fire.o\
MD_func.o\
MD_thermo.o\
run_md_classic.o\

OBJS_BASE=matrix3.o\
matrix.o\
intarray.o\
complexarray.o\
timer.o\
realarray.o\
global_file.o\
global_function.o\
global_variable.o\
tool_title.o\
tool_quit.o\
mymath3.o\