#
# The ABACUS-ORB module
#

VERSION= ABACUS-ORB
HEADERS= *.h

OBJS_BASE=math_integral.o\
math_sphbes.o\
math_polyint.o\
math_ylmreal.o\
ylm.o\
memory.o\
complexarray.o\
complexmatrix.o\
matrix.o\
realarray.o\
intarray.o\
sph_bessel.o\
sph_bessel_recursive-d1.o\
sph_bessel_recursive-d2.o\
tool_title.o\
tool_quit.o\
tool_check.o\
timer.o\
mathzone_add1.o\
global_variable.o\
global_function.o\
global_file.o\

OBJS_ORBITAL=ORB_control.o\
ORB_read.o\
ORB_atomic.o\
ORB_atomic_lm.o\
ORB_nonlocal.o\
ORB_nonlocal_lm.o\
ORB_gaunt_table.o\
ORB_table_beta.o\
ORB_table_phi.o\
ORB_table_alpha.o\
ORB_gen_tables.o\

OBJS_CTO=center2_orb-orb11.o\

OBJS_TEST=ORB_unittest.o\
1_snap_equal_test.o\
#2_snap_finite_diff_test.o\
#3_center2_finite_diff_test.o\