FORTRAN       = ifort

CPLUSPLUS      = icpc
#CPLUSPLUS     = /public/intel2017/bin/icpc

CPLUSPLUS_MPI = mpiicpc
#CPLUSPLUS_MPI = /public/intel2017/impi/2017.1.132/intel64/bin/mpiicpc

LAPACK_DIR    = $(MKLROOT)
#LAPACK_DIR = /public/intel2017/compilers_and_libraries_2017.1.132/linux/mkl
#LAPACK_DIR = $(MKLROOT)
#LAPACK_DIR    = /public/intel2017/mkl

#FFTW_DIR = /home/mohan/1_Software/impi_fftw-3.3.8
FFTW_DIR = /home/qianrui/intelcompile/impi_fftw
#FFTW_DIR       = /public/udata/xiaohui/software/fftw2
#FFTW_DIR       =/opt/fftw/3.3.6-p12/intel/2017.update4
#FFTW_DIR      = /public/fftw-3.3.8

#BOOST_DIR = /home/mohan/1_Software/impi_boost-1.70.0
BOOST_DIR = /home/qianrui/intelcompile/impi_boost
#BOOST_DIR      = /public/udata/xiaohui/software/boost_1_39_0
#BOOST_DIR      = /opt/boost/1.64.0

#ELPA_DIR = /home/mohan/1_Software/impi_elpa-16.05.005
ELPA_DIR = /home/qianrui/intelcompile/impi_elpa
#ELPA_DIR   = /public/udata/xiaohui/ELPA-2016.05.004
#ELPA_DIR = /opt/elpa/intel_2017_update4

#CEREAL_DIR = /home/mohan/1_Software/ABACUS_Github/cereal/cereal/
CEREAL_DIR = /home/qianrui/intelcompile/cereal/

OBJ_DIR = obj
NP      = 14
