FORTRAN        = ifort
CPLUSPLUS      = icpc
CPLUSPLUS_MPI  = mpiicpc
BOOST_DIR      = /public/home/linpz/software/boost-1.74.0
LAPACK_DIR     = /public/software/compiler/intel/parallel_studio_xe_2019_update3/compilers_and_libraries_2019/linux/mkl/
FFTW_DIR       = /public/home/linpz/software/fftw-3.3.8
ELPA_DIR       = /public/home/linpz/software/elpa-2016.05.004-openmp
LIBXC_DIR      = /public/home/linpz/software/libxc-5.0.0
CEREAL_DIR     = /public/home/linpz/software/cereal-master

OBJ_DIR = obj
NP      = 10
