FORTRAN       = ifort
CPLUSPLUS     = icpc
CPLUSPLUS_MPI = mpiicpc

LAPACK_DIR    = $(MKLROOT)

FFTW_DIR      = /public/software/fftw_3.3.8

ELPA_DIR      = /public/software/elpa_21.05.002
ELPA_INCLUDE_DIR = ${ELPA_DIR}/include/elpa-2021.05.002

CEREAL_DIR    = /home/qianrui/headfile/cereal

# LIBXC_DIR     = /public/software/libxc-5.0.0

# LIBTORCH_DIR  = /public/software/libtorch
# LIBNPY_DIR    = /public/software/libnpy

OBJ_DIR = obj
OBJ_DIR_serial = obj_serial
NP = 14
