name: Build Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - tag: gnu
          build_args: ""
          name: "Build with GNU compilers"
        - tag: gnu
          build_args: "-DENABLE_LIBXC=1"
          name: "Build with GNU compilers and extra components"
        - tag: intel
          build_args: ""
          name: "Build with Intel compilers"
        - tag: cuda
          build_args: "-DUSE_CUDA=1"
          name: "Build with CUDA kit"
    name: ${{ matrix.name }}
    container: ghcr.io/${{ github.repository_owner }}/abacus-development-kit:${{ matrix.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          cmake -B build -DBUILD_TESTING=ON ${{ matrix.build_args }}
          cmake --build build -j2
