name: CUDA Test

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test on CUDA Build
    runs-on: nvidia
    if: github.repository_owner == 'deepmodeling'
    container:
      image: ghcr.io/deepmodeling/abacus-cuda
      volumes:
        - /tmp/ccache:/github/home/.ccache
      options: --gpus all
      
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install Ccache
        run: |
          sudo apt-get update
          sudo apt-get install -y ccache

      - name: Configure & Build
        run: |
          nvidia-smi
          rm -rf build
          cmake -B build -DUSE_CUDA=ON -DBUILD_TESTING=ON
          cmake --build build -j4
          cmake --install build

      - name: Test 11_PW_GPU
        run: |
          cd tests/11_PW_GPU
          bash ../integrate/Autotest.sh -n 2 -f CASES_GPU.txt

      - name: Test 12_NAO_Gamma_GPU
        run: |
          cd tests/12_NAO_Gamma_GPU
          bash ../integrate/Autotest.sh -n 2 -f CASES_GPU.txt

      - name: Test 13_NAO_multik_GPU
        run: |
          cd tests/13_NAO_multik_GPU
          bash ../integrate/Autotest.sh -n 2 -f CASES_GPU.txt

      - name: Test 15_rtTDDFT_GPU
        run: |
          cd tests/15_rtTDDFT_GPU
          bash ../integrate/Autotest.sh -n 2 -f CASES_GPU.txt

      - name: Test 16_SDFT_GPU
        run: |
          cd tests/16_SDFT_GPU
          bash ../integrate/Autotest.sh -n 2 -f CASES_GPU.txt
