on: [push, pull_request]
env:
  PREFIX: ABACUS.develop
jobs:
  Build_on_GNU:
    runs-on: ubuntu-latest
    container: darelbeida/debian10:latest
    steps:
      - name: Setup env
        run: git config --global http.sslverify false && git config --global https.sslverify false
      - name: Download source codes
        uses: actions/checkout@v2
      - name: Build
        run: cd ${PREFIX}/source && GNU=1 make fp_mpi
      - name: Artifacts bins
        uses: actions/upload-artifact@v2
        with:
          name: bin
          path: ${{env.PREFIX}}/bin/*
          retention-days: 1

  Test:
    runs-on: ubuntu-latest
    container: darelbeida/debian10:latest
    needs: Build_on_GNU
    steps:
      - name: Setup env
        run: git config --global http.sslverify false && git config --global https.sslverify false
      - name: Download source codes
        uses: actions/checkout@v2
      - name: Reload bins
        uses: actions/download-artifact@v2
        with:
          name: bin
          path: ${{env.PREFIX}}/bin/
      - name: Test single
        run: |
          export PATH=$PATH:$PWD/${PREFIX}/bin
          export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
          chmod +x ${PREFIX}/bin/ABACUS.mpi
          cd ${PREFIX}/tests/
          cd 103_PW_15_CS_CF/
          ABACUS.mpi
