name: Integration Test and Unit Test

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: X64
    if: github.repository_owner == 'deepmodeling'
    container:
      image: ghcr.io/deepmodeling/abacus-gnu
      volumes:
        - /tmp/ccache:/github/home/.ccache
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          # We will handle submodules manually after fixing ownership
          submodules: 'false'

      - name: Take ownership of the workspace and update submodules
        run: |
          sudo chown -R $(whoami) .
          git submodule update --init --recursive

      - name: Install CI tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gfortran ccache ca-certificates python-is-python3 python3-pip
          sudo pip install clang-format clang-tidy

      - name: Install dftd4 from toolchain
        run: |
          cd toolchain
          ./install_abacus_toolchain_new.sh --with-dftd4=install --dry-run -j8
          ./scripts/stage4/install_dftd4.sh
          cd ..

      - name: Configure
        run: |
          source toolchain/install/setup
          cmake -B build -DBUILD_TESTING=ON -DENABLE_MLALGO=ON -DENABLE_LIBXC=ON -DENABLE_LIBRI=ON -DENABLE_GOOGLEBENCH=ON -DENABLE_RAPIDJSON=ON  -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DENABLE_FLOAT_FFTW=ON -DENABLE_DFTD4=ON

# Temporarily removed because no one maintains this now.
# And it will break the CI test workflow.

#      - uses: pre-commit/action@v3.0.1
#        with:
#          extra_args:
#            --from-ref ${{ github.event.pull_request.base.sha }}
#              --to-ref ${{ github.event.pull_request.head.sha }}
#        continue-on-error: true
#      - uses: pre-commit-ci/lite-action@v1.0.3

      - name: Build
        run: |
          cmake --build build -j8
          cmake --install build

      - name: Integrated Tests Preparation
        env:
          GTEST_COLOR: 'yes'
          OMP_NUM_THREADS: '2'
        run: |
          ctest --test-dir build -V --timeout 1700 -R integrated_test
          
      - name: Module_Base Unittests
        env:
          GTEST_COLOR: 'yes'
          OMP_NUM_THREADS: '2'
        run: |
          ctest --test-dir build -V --timeout 1700 -R MODULE_BASE
          
      - name: Module_IO Unittests
        env:
          GTEST_COLOR: 'yes'
          OMP_NUM_THREADS: '2'
        run: |
          ctest --test-dir build -V --timeout 1700 -R MODULE_IO
          
      - name: Module_HSolver Unittests
        env:
          GTEST_COLOR: 'yes'
          OMP_NUM_THREADS: '2'
        run: |
          ctest --test-dir build -V --timeout 1700 -R MODULE_HSOLVER -E PERF_MODULE_HSOLVER_KERNELS
          
      - name: Module_Cell Unittests
        env:
          GTEST_COLOR: 'yes'
          OMP_NUM_THREADS: '2'
        run: |
          ctest --test-dir build -V --timeout 1700 -R MODULE_CELL
          
      - name: Module_MD Unittests
        env:
          GTEST_COLOR: 'yes'
          OMP_NUM_THREADS: '2'
        run: |
          ctest --test-dir build -V --timeout 1700 -R MODULE_MD
          
      - name: Module_Psi Unittests
        env:
          GTEST_COLOR: 'yes'
          OMP_NUM_THREADS: '2'
        run: |
          ctest --test-dir build -V --timeout 1700 -R MODULE_PSI
          
      - name: Module_RI Unittests
        env:
          GTEST_COLOR: 'yes'
          OMP_NUM_THREADS: '2'
        run: |
          ctest --test-dir build -V --timeout 1700 -R MODULE_RI
      
      - name: Module_Estate Unittests
        env:
          GTEST_COLOR: 'yes'
          OMP_NUM_THREADS: '2'
        run: |
          ctest --test-dir build -V --timeout 1700 -R MODULE_ESTATE
      
      - name: Module_Hamilt Unittests
        env:
          GTEST_COLOR: 'yes'
          OMP_NUM_THREADS: '2'
        run: |
          ctest --test-dir build -V --timeout 1700 -R MODULE_HAMILT
      
      - name: Module_PW Unittests
        env:
          GTEST_COLOR: 'yes'
          OMP_NUM_THREADS: '2'
        run: |
          ctest --test-dir build -V --timeout 1700 -R MODULE_PW
      
      - name: Module_LCAO Unittests
        env:
          GTEST_COLOR: 'yes'
          OMP_NUM_THREADS: '2'
        run: |
          ctest --test-dir build -V --timeout 1700 -R MODULE_LCAO
      
      - name: Module_AO Unittests
        env:
          GTEST_COLOR: 'yes'
          OMP_NUM_THREADS: '2'
        run: |
          ctest --test-dir build -V --timeout 1700 -R MODULE_AO
      
      - name: Module_NAO Unittests
        env:
          GTEST_COLOR: 'yes'
          OMP_NUM_THREADS: '2'
        run: |
          ctest --test-dir build -V --timeout 1700 -R MODULE_NAO
      
      - name: Module_RELAX Unittests
        env:
          GTEST_COLOR: 'yes'
          OMP_NUM_THREADS: '2'
        run: |
          ctest --test-dir build -V --timeout 1700 -R MODULE_RELAX
      
      - name: Module_LR Unittests
        env:
          GTEST_COLOR: 'yes'
          OMP_NUM_THREADS: '2'
        run: |
          ctest --test-dir build -V --timeout 1700 -R MODULE_LR
          
      - name: 01_PW Test
        env:
          GTEST_COLOR: 'yes'
          OMP_NUM_THREADS: '2'
        run: |
          ctest --test-dir build -V --timeout 1700 -R 01_PW
          
      - name: 02_NAO_Gamma Test
        env:
          GTEST_COLOR: 'yes'
          OMP_NUM_THREADS: '2'
        run: |
          ctest --test-dir build -V --timeout 1700 -R 02_NAO_Gamma
          
      - name: 03_NAO_multik Test
        env:
          GTEST_COLOR: 'yes'
          OMP_NUM_THREADS: '2'
        run: |
          ctest --test-dir build -V --timeout 1700 -R 03_NAO_multik
          
      - name: 04_FF Test
        env:
          GTEST_COLOR: 'yes'
          OMP_NUM_THREADS: '2'
        run: |
          ctest --test-dir build -V --timeout 1700 -R 04_FF
          
      - name: 05_rtTDDFT Test
        env:
          GTEST_COLOR: 'yes'
          OMP_NUM_THREADS: '2'
        run: |
          ctest --test-dir build -V --timeout 1700 -R 05_rtTDDFT
          
      - name: 06_SDFT Test
        env:
          GTEST_COLOR: 'yes'
          OMP_NUM_THREADS: '2'
        run: |
          ctest --test-dir build -V --timeout 1700 -R 06_SDFT
          
      - name: 07_OFDFT Test
        env:
          GTEST_COLOR: 'yes'
          OMP_NUM_THREADS: '2'
        run: |
          ctest --test-dir build -V --timeout 1700 -R 07_OFDFT
          
      - name: 08_EXX Test
        env:
          GTEST_COLOR: 'yes'
          OMP_NUM_THREADS: '2'
        run: |
          ctest --test-dir build -V --timeout 1700 -R 08_EXX
          
      - name: 09_DeePKS Test
        env:
          GTEST_COLOR: 'yes'
          OMP_NUM_THREADS: '2'
        run: |
          ctest --test-dir build -V --timeout 1700 -R 09_DeePKS
          
      - name: 10_others Test
        env:
          GTEST_COLOR: 'yes'
          OMP_NUM_THREADS: '2'
        run: |
          ctest --test-dir build -V --timeout 1700 -R 10_others
          
      - name: Other Unittests
        env:
          GTEST_COLOR: 'yes'
          OMP_NUM_THREADS: '2'
        run: |
          ctest --test-dir build -V --timeout 1700 -E 'integrate_test|01_PW|02_NAO_Gamma|03_NAO_multik|04_FF|05_rtTDDFT|06_SDFT|07_OFDFT|08_EXX|09_DeePKS|10_others|11_PW_GPU|12_NAO_Gamma_GPU|13_NAO_multik_GPU|15_rtTDDFT_GPU|16_SDFT_GPU|MODULE_BASE|MODULE_IO|MODULE_HSOLVER|MODULE_CELL|MODULE_MD|MODULE_PSI|MODULE_ESTATE|MODULE_RI|MODULE_HAMILT|MODULE_PW|MODULE_LCAO|MODULE_AO|MODULE_NAO|MODULE_RELAX|MODULE_LR'
